-- ODSRISK.APPLICATION definition

CREATE TABLE "ODSRISK"."APPLICATION" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CIF_NO" VARCHAR2(50), 
	"MAIN_IDENTIFICATION_NUMBER" VARCHAR2(50), 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"REQUEST_PAYLOAD" CLOB, 
	"UPDATED_DATETIME" TIMESTAMP (6), 
	"VERSION" VARCHAR2(20) DEFAULT '1', 
	 CONSTRAINT "ID_NOT_NULL" CHECK (CIF_NO IS NOT NULL OR MAIN_IDENTIFICATION_NUMBER IS NOT NULL) ENABLE, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" 
 LOB ("REQUEST_PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "ODSRISK" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "ODSRISK"."SYS_C008055" ON "ODSRISK"."APPLICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  CREATE UNIQUE INDEX "ODSRISK"."SYS_IL0000076872C00005$$" ON "ODSRISK"."APPLICATION" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "ODSRISK"."APPLICATION_MAIN_IDENTIFICATION_NUMBER_INDEX" ON "ODSRISK"."APPLICATION" ("MAIN_IDENTIFICATION_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  CREATE INDEX "ODSRISK"."APPLICATION_CIF_NO_INDEX" ON "ODSRISK"."APPLICATION" ("CIF_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  CREATE INDEX "ODSRISK"."APPLICATION_REQUEST_PAYLOAD_CODE_BPM" ON "ODSRISK"."APPLICATION" (JSON_VALUE("REQUEST_PAYLOAD" FORMAT JSON , '$.application.applicationInfo.applicationCodeBPM' RETURNING VARCHAR2(50) NULL ON ERROR)) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  CREATE INDEX "ODSRISK"."APPLICATION_APPLICATION_DE_REF_NUMBER_IDX" ON "ODSRISK"."APPLICATION" ("APPLICATION_DE_REF_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;

GRANT SELECT ON "ODSRISK"."APPLICATION" TO "ODSRISK_READ";

COMMENT ON COLUMN ODSRISK.APPLICATION.VERSION IS 'Phân biết 1 là chưa tách BOM, 2 là tách BOM';




-- ODSRISK.APPLICATION_STATE definition

CREATE TABLE "ODSRISK"."APPLICATION_STATE" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"SOURCE_SYSTEM_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"STATE" VARCHAR2(50) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(100), 
	"CREATED_DATETIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"UPDATED_DATETIME" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"BPM_APPLICATION_ID" VARCHAR2(100), 
	"APPLICANT_MAIN_NAME" VARCHAR2(100), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;

CREATE INDEX "ODSRISK"."APPLICATION_STATE_CREATED_DATETIME_INDEX" ON "ODSRISK"."APPLICATION_STATE" ("CREATED_DATETIME" DESC) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  CREATE UNIQUE INDEX "ODSRISK"."SYS_C008051" ON "ODSRISK"."APPLICATION_STATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  CREATE INDEX "ODSRISK"."APPLICATION_STATE_APPLICATION_DE_REF_NUMBER_IDX" ON "ODSRISK"."APPLICATION_STATE" ("APPLICATION_DE_REF_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;

GRANT SELECT ON "ODSRISK"."APPLICATION_STATE" TO "ODSRISK_READ";




-- ODSRISK.INTEGRATION_EVENT_LOG definition

CREATE TABLE "ODSRISK"."INTEGRATION_EVENT_LOG" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(255) NOT NULL ENABLE, 
	"APPLICANT_MAIN_ID" VARCHAR2(50), 
	"APPLICANT_ID" VARCHAR2(50), 
	"APPLICANT_TYPE" VARCHAR2(50), 
	"CALL_TYPE" VARCHAR2(30), 
	"SYSTEM" VARCHAR2(20) NOT NULL ENABLE, 
	"REQUEST_PAYLOAD" CLOB, 
	"RESPONSE_PAYLOAD" CLOB, 
	"STATUS" VARCHAR2(20), 
	"START_DATETIME" TIMESTAMP (6), 
	"END_DATETIME" TIMESTAMP (6), 
	"CREATED_DATETIME" TIMESTAMP (6), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" 
 LOB ("REQUEST_PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "ODSRISK" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESPONSE_PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "ODSRISK" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "ODSRISK"."SYS_C008065" ON "ODSRISK"."INTEGRATION_EVENT_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  CREATE UNIQUE INDEX "ODSRISK"."SYS_IL0000076886C00009$$" ON "ODSRISK"."INTEGRATION_EVENT_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "ODSRISK"."SYS_IL0000076886C00008$$" ON "ODSRISK"."INTEGRATION_EVENT_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE INDEX "ODSRISK"."INTEGRATION_EVENT_LOG_APPLICATION_DE_REF_NUMBER_IDX" ON "ODSRISK"."INTEGRATION_EVENT_LOG" ("APPLICATION_DE_REF_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  
  
  
  -- ODSRISK.MODEL_EXECUTION_LOG definition

CREATE TABLE "ODSRISK"."MODEL_EXECUTION_LOG" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"CUSTOMER_ID" VARCHAR2(50), 
	"CALL_TYPE" VARCHAR2(30), 
	"MODEL_NAME" VARCHAR2(50), 
	"INPUT" CLOB, 
	"OUTPUT" CLOB, 
	"CREATED_DATETIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" 
 LOB ("INPUT") STORE AS SECUREFILE (
  TABLESPACE "ODSRISK" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("OUTPUT") STORE AS SECUREFILE (
  TABLESPACE "ODSRISK" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "ODSRISK"."SYS_C008041" ON "ODSRISK"."MODEL_EXECUTION_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  CREATE UNIQUE INDEX "ODSRISK"."SYS_IL0000076859C00007$$" ON "ODSRISK"."MODEL_EXECUTION_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "ODSRISK"."SYS_IL0000076859C00006$$" ON "ODSRISK"."MODEL_EXECUTION_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;

GRANT SELECT ON "ODSRISK"."MODEL_EXECUTION_LOG" TO "ODSRISK_READ";



-- ODSRISK.PREVIOUS_POLICY_DECISION definition

CREATE TABLE "ODSRISK"."PREVIOUS_POLICY_DECISION" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(50), 
	"APPLICANT_IDS" VARCHAR2(250), 
	"PHONE_NUMBER" VARCHAR2(20), 
	"RULE_ACTION" VARCHAR2(30), 
	"REASON_CODE" VARCHAR2(100), 
	"REASON_DESCRIPTION" VARCHAR2(200), 
	"RULE_CATEGORY" VARCHAR2(50), 
	"APPLICANT_TYPE" VARCHAR2(100), 
	"RESULT_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CREATE_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;

CREATE OR REPLACE EDITIONABLE TRIGGER "ODSRISK"."DR$IDX_PPD_APPLICANT_IDSTC" after insert or update on "ODSRISK"."PREVIOUS_POLICY_DECISION" for each row declare   reindex boolean := FALSE;   updop   boolean := FALSE; begin   ctxsys.drvdml.c_updtab.delete;   ctxsys.drvdml.c_numtab.delete;   ctxsys.drvdml.c_vctab.delete;   ctxsys.drvdml.c_rowid := :new.rowid;   if (inserting or updating('APPLICANT_IDS') or       :new."APPLICANT_IDS" <> :old."APPLICANT_IDS") then     reindex := TRUE;     updop := (not inserting);     ctxsys.drvdml.c_text_vc2 := :new."APPLICANT_IDS";   end if;   ctxsys.drvdml.ctxcat_dml('ODSRISK','IDX_PPD_APPLICANT_IDS', reindex, updop); end;
/
ALTER TRIGGER "ODSRISK"."DR$IDX_PPD_APPLICANT_IDSTC" ENABLE;
BEGIN 
  DBMS_DDL.SET_TRIGGER_FIRING_PROPERTY('"ODSRISK"','"DR$IDX_PPD_APPLICANT_IDSTC"',FALSE) ; 
END;
/

CREATE UNIQUE INDEX "ODSRISK"."SYS_C008057" ON "ODSRISK"."PREVIOUS_POLICY_DECISION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;
  CREATE INDEX "ODSRISK"."IDX_PPD_APPLICANT_IDS" ON "ODSRISK"."PREVIOUS_POLICY_DECISION" ("APPLICANT_IDS") 
   INDEXTYPE IS "CTXSYS"."CTXCAT" ;
  CREATE INDEX "ODSRISK"."IDX_PPD_PHONE_NUMBER" ON "ODSRISK"."PREVIOUS_POLICY_DECISION" ("PHONE_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODSRISK" ;

GRANT SELECT ON "ODSRISK"."PREVIOUS_POLICY_DECISION" TO "ODSRISK_READ";