-- DROP USER DE_CBC_RAW_DE;

CREATE USER DE_CBC_RAW_DE
-- IDENTIFIED BY <password>
;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_A05" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"RESPONSE_CODE" VARCHAR2(4000), 
	"RESPONSE_MESSAGE" VARCHAR2(4000), 
	"ACCOUNT_NUMBER" VARCHAR2(4000), 
	"ACCOUNT_NAME" VARCHAR2(4000), 
	"RISK_LEVEL" VARCHAR2(4000), 
	"MESSAGE" VARCHAR2(4000), 
	"REQUEST_ID" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_A05_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_A05_PK" ON "DE_CBC_RAW_DE"."DE_CBC_A05" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_ACC_DETAIL" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CIF_NUMBER" VARCHAR2(4000), 
	"VAR_NAME" VARCHAR2(4000), 
	"VAR_VALUE" VARCHAR2(4000), 
	"ACC_TYPE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_ACC_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_ACC_DETAIL_PK" ON "DE_CBC_RAW_DE"."DE_CBC_ACC_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_ADDRESS" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"ADDRESS_TYPE" VARCHAR2(4000), 
	"PROVINCE_CODE" VARCHAR2(4000), 
	"PROVINCE_NAME" VARCHAR2(4000), 
	"DISTRICT_CODE" VARCHAR2(4000), 
	"DISTRICT_NAME" VARCHAR2(4000), 
	"STREET" VARCHAR2(255), 
	"WARD_CODE" VARCHAR2(4000), 
	"WARD_NAME" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_ADDRESS_PK" ON "DE_CBC_RAW_DE"."DE_CBC_ADDRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_AML" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"AML_LIST_NAME" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_AML_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_AML_PK" ON "DE_CBC_RAW_DE"."DE_CBC_AML" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_APPLICANT" 
   (	"ID" NUMBER, 
	"APPLICATION_ID" VARCHAR2(4000), 
	"APPLICANT_TYPE" VARCHAR2(4000), 
	"CUSTOMER_SEGMENT" VARCHAR2(4000), 
	"APPLICANT_NAME" VARCHAR2(4000), 
	"CIF_NUMBER" VARCHAR2(4000), 
	"DOB" VARCHAR2(4000), 
	"AGE" NUMBER, 
	"GENDER" VARCHAR2(4000), 
	"NATIONALITY" VARCHAR2(4000), 
	"PHONE" VARCHAR2(4000), 
	"EMAIL" VARCHAR2(4000), 
	"MARITAL_STATUS" VARCHAR2(4000), 
	"JOB" VARCHAR2(4000), 
	"AGENCY_POSITION" VARCHAR2(4000), 
	"OVERALL_SCORE" NUMBER, 
	"RECORDED_INCOME" NUMBER, 
	"INCOME_FROM_MODEL" NUMBER, 
	"MODEL_ACCEPT_BEFORE_MODEL_FLOW" VARCHAR2(4000), 
	"FLAG_ACCEPT_MODEL" VARCHAR2(4000), 
	"MODEL_FLOW_POINT" VARCHAR2(4000), 
	"OVERALL_MODEL_RATING" VARCHAR2(4000), 
	"INCOME_METHOD" VARCHAR2(4000), 
	"CONVERSION_METHOD" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	"IS_NTB" VARCHAR2(4000), 
	"IS_SECURE" VARCHAR2(4000), 
	 CONSTRAINT "DE_CBC_APPLICANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_APPLICANT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_APPLICANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

COMMENT ON COLUMN DE_CBC_RAW_DE.DE_CBC_APPLICANT.IS_NTB IS 'KH là new to Bank';
COMMENT ON COLUMN DE_CBC_RAW_DE.DE_CBC_APPLICANT.IS_SECURE IS 'KH có thế chấp';

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_APPLICANT_VARIABLE" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"VAR_NAME" VARCHAR2(4000), 
	"VAR_VALUE" VARCHAR2(4000), 
	"VAR_TYPE" VARCHAR2(4000), 
	"VAR_GROUP" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_APPLICANT_VARIABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_APPLICANT_VARIABLE_PK" ON "DE_CBC_RAW_DE"."DE_CBC_APPLICANT_VARIABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_APPLICATION" 
   (	"APPLICATION_ID" VARCHAR2(4000), 
	"APPLICATION_CODE_MBA" VARCHAR2(4000), 
	"SOURCE" VARCHAR2(4000), 
	"APPLICATION_CODE_BPM" VARCHAR2(4000), 
	"APPLICATION_FLOW" VARCHAR2(4000), 
	"APPLICATION_CREATE_TIME" VARCHAR2(4000), 
	"APPLICATION_SALE_ID" VARCHAR2(4000), 
	"RECOMMENDED_DECISION" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_APPLICATION_PK" PRIMARY KEY ("APPLICATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_APPLICATION_PK" ON "DE_CBC_RAW_DE"."DE_CBC_APPLICATION" ("APPLICATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_APPLICATION_VARIABLE" 
   (	"ID" NUMBER, 
	"APPLICATION_ID" VARCHAR2(4000), 
	"PRODUCT_ID" NUMBER, 
	"VAR_NAME" VARCHAR2(4000), 
	"VAR_VALUE" VARCHAR2(4000), 
	"VAR_TYPE" VARCHAR2(4000), 
	"VAR_GROUP" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_APPLICATION_VARIABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_APPLICATION_VARIABLE_PK" ON "DE_CBC_RAW_DE"."DE_CBC_APPLICATION_VARIABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_C06" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CARD_NO" VARCHAR2(4000), 
	"STATUS" VARCHAR2(4000), 
	"MESSAGE" VARCHAR2(4000), 
	"OLD_ID_CARD_NO" VARCHAR2(4000), 
	"ADDRESS" VARCHAR2(4000), 
	"PLACE_OF_ORIGIN" VARCHAR2(4000), 
	"MOTHER_NAME" VARCHAR2(4000), 
	"SPOUSE_NAME" VARCHAR2(4000), 
	"FATHER_NAME" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_C06_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_C06_PK" ON "DE_CBC_RAW_DE"."DE_CBC_C06" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_CARD_CONTRACT" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"SOURCE_SYSTEM" VARCHAR2(4000), 
	"CONTRACT_ID" VARCHAR2(4000), 
	"CONTRACT_NUMBER" VARCHAR2(4000), 
	"AUTH_LIMIT_AMOUNT" NUMBER, 
	"GTTT" VARCHAR2(4000), 
	"APPLICATION_CODE" VARCHAR2(4000), 
	"SECURED" VARCHAR2(4000), 
	"COLLATCODE_FLAG" VARCHAR2(4000), 
	"APPROVAL_TIME" DATE, 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_CARD_CONTRACT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_CARD_CONTRACT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_CARD_CONTRACT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_CARD_DETAIL" 
   (	"ID" NUMBER, 
	"CARD_CONTRACT_ID" NUMBER, 
	"CIF_NO" VARCHAR2(4000), 
	"STATUS" VARCHAR2(4000), 
	"PRODUCT_CODE" VARCHAR2(4000), 
	"PRODUCT_INFO" VARCHAR2(4000), 
	"SOURCE_SYSTEM" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_CARD_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_CARD_DETAIL_PK" ON "DE_CBC_RAW_DE"."DE_CBC_CARD_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_CASA_INFO" 
   (	"ID" NUMBER, 
	"LEAD_REFER_ID" NUMBER, 
	"INCOME_POLICY_CODE" VARCHAR2(4000), 
	"SALARY_MSB_01" NUMBER, 
	"SALARY_MSB_02" NUMBER, 
	"SALARY_MSB_03" NUMBER, 
	"CASA_BALANCE_01" NUMBER, 
	"CASA_BALANCE_02" NUMBER, 
	"CASA_BALANCE_03" NUMBER, 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_CASA_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_CASA_INFO_PK" ON "DE_CBC_RAW_DE"."DE_CBC_CASA_INFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_CIC" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CLIENT_QUESTION_ID" VARCHAR2(4000), 
	"STATUS" VARCHAR2(4000), 
	"REPORT_DATE" DATE, 
	"TRANSACTION_TIME" DATE, 
	"CODE_MESSAGE" VARCHAR2(4000), 
	"TAX_NO" VARCHAR2(4000), 
	"BUSINESS_REGISTRATION_NUMBER" VARCHAR2(4000), 
	"CUSTOMER_IDENTIFICATION_NUMBER" VARCHAR2(4000), 
	"CIC_CODE" VARCHAR2(4000), 
	"ADDRESS" VARCHAR2(4000), 
	"CUSTOMER_NAME" VARCHAR2(4000), 
	"PHONE_NUMBER" VARCHAR2(4000), 
	"DIRECTOR_NAME" VARCHAR2(4000), 
	"FINANCIAL_YEAR" VARCHAR2(4000), 
	"NOTE" VARCHAR2(4000), 
	"GROUP" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_CIC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_CIC_PK" ON "DE_CBC_RAW_DE"."DE_CBC_CIC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_CIC_DERIVED_VARIABLE" 
   (	"ID" NUMBER, 
	"CIC_ID" NUMBER, 
	"VAR_NAME" VARCHAR2(4000), 
	"VAR_VALUE" VARCHAR2(4000), 
	"GROUP" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_CIC_DERIVED_VARIABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_CIC_DERIVED_VARIABLE_PK" ON "DE_CBC_RAW_DE"."DE_CBC_CIC_DERIVED_VARIABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_ERROR" 
   (	"APPLICATION_ID" VARCHAR2(4000), 
	"ERROR_CODE" CLOB, 
	"ERROR_DESCRIPTION" VARCHAR2(1000), 
	"SOURCE" VARCHAR2(4000), 
	"DATETIME" VARCHAR2(4000), 
	"TRACE" CLOB, 
	"CREATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

 LOB ("ERROR_CODE") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("TRACE") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_EXISTS_IDENTIFICATION" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CIF_NUMBER" VARCHAR2(4000), 
	"GTTT" VARCHAR2(4000), 
	"IDENTIFICATION_TYPE" VARCHAR2(4000), 
	"AML_LIST_NAME" VARCHAR2(4000), 
	"ACCOUNT_NO" VARCHAR2(4000), 
	"CARD_NO" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	"OPEN_DATE" DATE, 
	 CONSTRAINT "DE_CBC_EXISTS_IDENTIFICATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_EXISTS_IDENTIFICATION_PK" ON "DE_CBC_RAW_DE"."DE_CBC_EXISTS_IDENTIFICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

COMMENT ON COLUMN DE_CBC_RAW_DE.DE_CBC_EXISTS_IDENTIFICATION.OPEN_DATE IS 'Ngày mở CIF';

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_FRAUD_RULE_BANKING" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CIF" VARCHAR2(4000), 
	"NAME" VARCHAR2(4000), 
	"NAME_CLN" VARCHAR2(4000), 
	"CONTACT_TYPE" VARCHAR2(4000), 
	"CONTACT_INFO" VARCHAR2(4000), 
	"CONTACT_INFO_CLN" VARCHAR2(4000), 
	"SOURCE_SYSTEM" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_FRAUD_RULE_BANKING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_FRAUD_RULE_BANKING_PK" ON "DE_CBC_RAW_DE"."DE_CBC_FRAUD_RULE_BANKING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_FRAUD_RULE_CAPITAL" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"MSB_EQUITY" VARCHAR2(4000), 
	"EFFECTIVE_DATE" VARCHAR2(4000), 
	"STATUS" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_FRAUD_RULE_CAPITAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_FRAUD_RULE_CAPITAL_PK" ON "DE_CBC_RAW_DE"."DE_CBC_FRAUD_RULE_CAPITAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_FRAUD_RULE_RB_APPROVAL" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CIF" VARCHAR2(4000), 
	"APPLICATION_CODE" VARCHAR2(4000), 
	"NAME" VARCHAR2(4000), 
	"NAME_CLN" VARCHAR2(4000), 
	"PHONE" VARCHAR2(4000), 
	"PHONE_CLN" VARCHAR2(4000), 
	"RELATION_CODE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_FRAUD_RULE_RB_APPROVAL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_FRAUD_RULE_RB_APPROVAL_PK" ON "DE_CBC_RAW_DE"."DE_CBC_FRAUD_RULE_RB_APPROVAL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_IDENTIFICATION" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"IS_MAIN_IDENTIFICATION" VARCHAR2(4000), 
	"IDENTIFICATION_NUMBER" VARCHAR2(4000), 
	"PLACE_OF_ISSUE" VARCHAR2(4000), 
	"DATE_OF_ISSUE" DATE, 
	"DATE_OF_EXPIRE" DATE, 
	"IDENTIFICATION_TYPE_MAIN" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_IDENTIFICATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_IDENTIFICATION_PK" ON "DE_CBC_RAW_DE"."DE_CBC_IDENTIFICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_INCOME_DETAIL" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"INCOME_MONTH" NUMBER, 
	"INCOME_TYPE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_INCOME_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_INCOME_DETAIL_PK" ON "DE_CBC_RAW_DE"."DE_CBC_INCOME_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_LEAD_DETAIL" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"LEAD_ID" VARCHAR2(4000), 
	"LEAD_NAME" VARCHAR2(4000), 
	"LEAD_TYPE" VARCHAR2(4000), 
	"LEAD_LIMIT" NUMBER, 
	"CREDIT_CARD_LIMIT" NUMBER, 
	"EFFECTIVE_DATE" DATE, 
	"EXPERY_DATE" DATE, 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_LEAD_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_LEAD_DETAIL_PK" ON "DE_CBC_RAW_DE"."DE_CBC_LEAD_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_LEAD_MODEL_INFO" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"RANK" VARCHAR2(4000), 
	"MODEL_TYPE_CODE" VARCHAR2(4000), 
	"PRODUCT_CLASS" VARCHAR2(4000), 
	"RANK_ORDER" NUMBER, 
	"EFFECTIVE_DATE" DATE, 
	"EXPIRE_DATE" DATE, 
	"CUST_ID" VARCHAR2(4000), 
	"CIF_NUMBER" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	"MODEL_INFO_CODE" VARCHAR2(4000), 
	"RECOMMENDATION" VARCHAR2(4000), 
	"FINAL_SCORE" NUMBER, 
	"MODEL_GROUP_NAME" VARCHAR2(100), 
	"LOAN_METHOD" VARCHAR2(100), 
	"PRODUCT_CATEGORY" VARCHAR2(100), 
	"TYPE_OF_MODEL" VARCHAR2(100), 
	"SCORING_DATE" DATE, 
	 CONSTRAINT "DE_CBC_LEAD_MODEL_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_LEAD_MODEL_INFO_PK" ON "DE_CBC_RAW_DE"."DE_CBC_LEAD_MODEL_INFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_LOAN_CONTRACT" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CONTRACT_ID" VARCHAR2(4000), 
	"CIF" VARCHAR2(4000), 
	"ACF_STATUS" VARCHAR2(4000), 
	"EXPIRY_DATE" DATE, 
	"AMOUNT_APPROVED" NUMBER, 
	"APPROVAL_TIME" DATE, 
	"SECURED" VARCHAR2(4000), 
	"COLLATCODE_FLAG" VARCHAR2(4000), 
	"REVOL_NON_REVOL" VARCHAR2(4000), 
	"GTTT" VARCHAR2(4000), 
	"SOURCE_SYSTEM" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_LOAN_CONTRACT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_LOAN_CONTRACT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_LOAN_CONTRACT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_LOAN_DETAIL" 
   (	"ID" NUMBER, 
	"LOAN_CONTRACT_ID" NUMBER, 
	"CIF_NO" VARCHAR2(4000), 
	"LOAN_ACCOUNT_NUMBER" VARCHAR2(4000), 
	"PRODUCT_CODE" VARCHAR2(4000), 
	"PRODUCT_INFO" VARCHAR2(4000), 
	"PAYMENT_CODE" VARCHAR2(4000), 
	"AMOUNT" NUMBER, 
	"OUTSTANDING_BALANCE" NUMBER, 
	"PAYMENT_AMT" NUMBER, 
	"REMAINING_MONTHS" NUMBER, 
	"LIMIT_TERM" NUMBER, 
	"DISBURSED_AMT" NUMBER, 
	"STATUS" VARCHAR2(4000), 
	"SOURCE_SYSTEM" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_LOAN_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_LOAN_DETAIL_PK" ON "DE_CBC_RAW_DE"."DE_CBC_LOAN_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_MODEL_CIC" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CLIENT_QUESTION_ID" VARCHAR2(4000), 
	"STATUS" VARCHAR2(5), 
	"REPORT_DATE" DATE, 
	"TRANSACTION_TIME" DATE, 
	"CODE_MESSAGE" VARCHAR2(4000), 
	"TAX_NO" VARCHAR2(4000), 
	"BUSINESS_REGISTRATION_NUMBER" VARCHAR2(4000), 
	"CUSTOMER_IDENTIFICATION_NUMBER" VARCHAR2(4000), 
	"CIC_CODE" VARCHAR2(4000), 
	"ADDRESS" VARCHAR2(4000), 
	"CUSTOMER_NAME" VARCHAR2(4000), 
	"PHONE_NUMBER" VARCHAR2(4000), 
	"DIRECTOR_NAME" VARCHAR2(4000), 
	"FINANCIAL_YEAR" VARCHAR2(4000), 
	"NOTE" VARCHAR2(4000), 
	"GROUP" VARCHAR2(15), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_MODEL_CIC_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_MODEL_CIC_PK" ON "DE_CBC_RAW_DE"."DE_CBC_MODEL_CIC" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_MODEL_CIC_DERIVED_VARIABLE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CIC_ID" NUMBER, 
	"VAR_NAME" VARCHAR2(4000), 
	"VAR_VALUE" VARCHAR2(4000), 
	"GROUP" VARCHAR2(15), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_MODLE_CIC_DERIVED_VARIABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_MODLE_CIC_DERIVED_VARIABLE_PK" ON "DE_CBC_RAW_DE"."DE_CBC_MODEL_CIC_DERIVED_VARIABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_MODEL_INFO" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CUST_ID" VARCHAR2(4000), 
	"CIF_NUMBER" VARCHAR2(4000), 
	"MODEL_INFO_CODE" VARCHAR2(4000), 
	"MODEL_TYPE_CODE" VARCHAR2(4000), 
	"TYPE_OF_MODEL" VARCHAR2(4000), 
	"TYPE_OF_SEGMENT" VARCHAR2(4000), 
	"SEGMENT_RESULT" VARCHAR2(4000), 
	"ML_FLG" VARCHAR2(4000), 
	"IS_MODEL_AUTO" VARCHAR2(4000), 
	"SUB_MODEL_TYPE" VARCHAR2(4000), 
	"OVERRIDE_TOLERANCE_SUB" VARCHAR2(4000), 
	"IS_SEGMENT_MODEL" VARCHAR2(4000), 
	"MODEL_CATEGORY" VARCHAR2(4000), 
	"MODEL_TYPE_SCORE_DIRECTION" VARCHAR2(4000), 
	"MODEL_SEQUENCE_NO" NUMBER, 
	"CREATED_DATE" DATE, 
	"APPLICANT_ID" VARCHAR2(4000), 
	"FLAG_EXECUTE_STATUS" VARCHAR2(4000), 
	"MODEL_GROUP_NAME" VARCHAR2(4000), 
	"LOAN_METHOD" VARCHAR2(4000), 
	"PRODUCT_CATEGORY" VARCHAR2(4000), 
	"LOAN_METHOD_REQUEST" VARCHAR2(4000), 
	"PRODUCT_CATEGORY_REQUEST" VARCHAR2(4000), 
	"IS_NEXT_MODEL" VARCHAR2(4000), 
	 CONSTRAINT "DE_CBC_MODEL_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_MODEL_INFO_PK" ON "DE_CBC_RAW_DE"."DE_CBC_MODEL_INFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_MODEL_INTERNAL_DATA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CIF_NUMBER" VARCHAR2(4000), 
	"VAR_NAME" VARCHAR2(4000), 
	"VAR_VALUE" VARCHAR2(4000), 
	"ACC_TYPE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_MODEL_INTERNAL_DATA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_MODEL_INTERNAL_DATA_PK" ON "DE_CBC_RAW_DE"."DE_CBC_MODEL_INTERNAL_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_MODEL_OUTPUT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"APPLICANT_REFER_ID" NUMBER, 
	"RANK" VARCHAR2(4000), 
	"MODEL_TYPE_CODE" VARCHAR2(4000), 
	"PRODUCT_CATEGORY" VARCHAR2(4000), 
	"RANK_ORDER" VARCHAR2(4000), 
	"MODEL_GROUP_NAME" VARCHAR2(4000), 
	"TYPE_OF_MODEL" VARCHAR2(4000), 
	"LOAN_METHOD" VARCHAR2(4000), 
	"RECOMMENDATION" VARCHAR2(4000), 
	"FINAL_SCORE" NUMBER, 
	"SCORING_DATE" DATE, 
	"SPECIALIZED_BANK" VARCHAR2(4000), 
	"CUST_ID" VARCHAR2(4000), 
	"CIF_NUMBER" VARCHAR2(4000), 
	"IS_MODEL_SELECTED" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_MODEL_OUTPUT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_MODEL_OUTPUT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_MODEL_OUTPUT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_MODEL_RESULT" 
   (	"ID" NUMBER, 
	"MODEL_INFO_ID" NUMBER, 
	"MODEL_TYPE_SCORE_DIRECTION" VARCHAR2(4000), 
	"OVERRIDE_VALUE" NUMBER, 
	"SPECIALIZED_BANK" VARCHAR2(4000), 
	"STANDARDISED_SCORE" NUMBER, 
	"OVERRIDE_LEVEL" VARCHAR2(4000), 
	"SCORE" NUMBER, 
	"SCORE_PD" NUMBER, 
	"UNCALIBRATED_PD" NUMBER, 
	"CALIBRATED_PD" NUMBER, 
	"FINAL_SCORE" NUMBER, 
	"RANK" VARCHAR2(4000), 
	"RANK_ORDER" NUMBER, 
	"RECOMMENDATION" VARCHAR2(4000), 
	"RESULT_STATUS_CODE" VARCHAR2(4000), 
	"IS_MODEL_SELECTED" VARCHAR2(4000), 
	"IS_OVERRIDE" VARCHAR2(4000), 
	"IS_TOLERRANCE" VARCHAR2(4000), 
	"IS_SUB_AFFECT" VARCHAR2(4000), 
	"EXPIRY_DATE" DATE, 
	"SCORING_DATE" DATE, 
	"CREATED_DATE" DATE, 
	"STEP_FINAL" NUMBER, 
	"PRODUCT_CLASS" VARCHAR2(4000), 
	 CONSTRAINT "DE_CBC_MODEL_RESULT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_MODEL_RESULT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_MODEL_RESULT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_MODEL_SCORING_CONSTANT" 
   (	"ID" NUMBER, 
	"MODEL_INFO_ID" NUMBER, 
	"CONSTANT_CODE" VARCHAR2(4000), 
	"CONSTANT_VALUE" NUMBER, 
	"CONSTANT_ORDER" NUMBER, 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_MODEL_SCORING_CONSTANT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_MODEL_SCORING_CONSTANT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_MODEL_SCORING_CONSTANT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_MODEL_TYPE_QUES_GROUP" 
   (	"ID" NUMBER, 
	"MODEL_INFO_ID" NUMBER, 
	"CODE" VARCHAR2(4000), 
	"NAME" VARCHAR2(4000), 
	"WEIGHT" NUMBER, 
	"STD" NUMBER, 
	"MEAN" NUMBER, 
	"SCORE" NUMBER, 
	"STANDARDIZE_SCORE" NUMBER, 
	"CREATED_DATE" DATE, 
	"STEP_FINAL" VARCHAR2(4000), 
	"PRODUCT_CLASS" VARCHAR2(4000), 
	 CONSTRAINT "DE_CBC_MODEL_TYPE_QUES_GROUP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_MODEL_TYPE_QUES_GROUP_PK" ON "DE_CBC_RAW_DE"."DE_CBC_MODEL_TYPE_QUES_GROUP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_MODEL_VARIABLE" 
   (	"ID" NUMBER, 
	"MODEL_INFO_ID" NUMBER, 
	"QUESTION_CODE" VARCHAR2(4000), 
	"ANS_DATA_TYPE" VARCHAR2(4000), 
	"ANSWER_VALUE" VARCHAR2(4000), 
	"MODEL_TYPE_CODE" VARCHAR2(4000), 
	"DATE_ANSWER" DATE, 
	"MODEL_TYPE_QUES_CODE" VARCHAR2(4000), 
	"CALCULATE_LEVEL" NUMBER, 
	"MODEL_TYPE_QUES_GROUP" VARCHAR2(4000), 
	"WEIGHT" NUMBER, 
	"MEAN" NUMBER, 
	"STD" NUMBER, 
	"IS_SUB_ACCOMPANY" VARCHAR2(4000), 
	"IS_TOLERANCE" VARCHAR2(4000), 
	"TOLERANCE_UNIT" VARCHAR2(4000), 
	"TOLERANCE_VALUE" NUMBER, 
	"IS_OVERRIDE" VARCHAR2(4000), 
	"OVERRIDE_TYPE" VARCHAR2(4000), 
	"OVERRIDE_VALUE" NUMBER, 
	"ML_QUESTION_CODE" VARCHAR2(4000), 
	"NUMERIC_ANSWER" NUMBER, 
	"BOOLEAN_ANSWER" VARCHAR2(4000), 
	"STRING_ANSWER" VARCHAR2(4000), 
	"PARTIAL_SCORE" NUMBER, 
	"STANDARDIZE_SCORE" NUMBER, 
	"REASON_CODE" VARCHAR2(4000), 
	"ANSWER_ORDER" NUMBER, 
	"SCORE_ORDER" NUMBER, 
	"IS_TOLERANCE_APPLIED" VARCHAR2(4000), 
	"IS_OVERRIDE_APPLIED" VARCHAR2(4000), 
	"RANK_ORDER" NUMBER, 
	"CREATED_DATE" DATE, 
	"OVERRIDE_DIRECTION" VARCHAR2(4000), 
	"INT_OR_REAL_ANSWER" NUMBER, 
	"OVERRIDEN_RANK" NUMBER, 
	 CONSTRAINT "DE_CBC_MODEL_VARIABLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_MODEL_VARIABLE_PK" ON "DE_CBC_RAW_DE"."DE_CBC_MODEL_VARIABLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_OD_CONTRACT" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CONTRACT_ID" VARCHAR2(4000), 
	"SOURCE_SYSTEM" VARCHAR2(4000), 
	"CIF_NO" VARCHAR2(4000), 
	"OVERDRAFT_LIMIT" NUMBER, 
	"SECURED" VARCHAR2(4000), 
	"COLLATCODE_FLAG" VARCHAR2(4000), 
	"OVERDRAFT_EXPIRY_DATE" DATE, 
	"GTTT" VARCHAR2(4000), 
	"APPLICATION_CODE" VARCHAR2(4000), 
	"APPROVAL_TIME" DATE, 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_OD_CONTRACT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_OD_CONTRACT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_OD_CONTRACT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_OD_DETAIL" 
   (	"ID" NUMBER, 
	"OD_CONTRACT_ID" NUMBER, 
	"CIF_NO" VARCHAR2(4000), 
	"OVERDRAFT_ACCOUNT" VARCHAR2(4000), 
	"OVERDRAFT_OUTSTANDING_BALANCE" NUMBER, 
	"PRODUCT_CODE" VARCHAR2(4000), 
	"PRODUCT_INFO" VARCHAR2(4000), 
	"STATUS" VARCHAR2(4000), 
	"SOURCE_SYSTEM" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_OD_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_OD_DETAIL_PK" ON "DE_CBC_RAW_DE"."DE_CBC_OD_DETAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_OFFER" 
   (	"ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"APPROVED_CREDIT_OR_LOAN_LIMIT" NUMBER, 
	"APPROVAL_TERM" NUMBER, 
	"APPROVAL_VALIDITY" DATE, 
	"APPROVAL_TIME" DATE, 
	"INTEREST_RATE" NUMBER, 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_OFFER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_OFFER_PK" ON "DE_CBC_RAW_DE"."DE_CBC_OFFER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_OPRISK" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"ADDRESS" VARCHAR2(4000), 
	"BRANCH_INPUT" VARCHAR2(100), 
	"CUS_ID" VARCHAR2(4000), 
	"DATE_EX" DATE, 
	"DATE_INPUT" DATE, 
	"DOB" DATE, 
	"DSCN" VARCHAR2(4000), 
	"DTCN" VARCHAR2(4000), 
	"ERROR_MESS" VARCHAR2(4000), 
	"ID_OPRISK" VARCHAR2(4000), 
	"INPUT_USER" VARCHAR2(4000), 
	"NAME" VARCHAR2(4000), 
	"RECORD_ID" VARCHAR2(4000), 
	"RESULT" VARCHAR2(4000), 
	"VERSION" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_OPRISK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_OPRISK_PK" ON "DE_CBC_RAW_DE"."DE_CBC_OPRISK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_OVERDUE_ACCOUNT" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CIF" VARCHAR2(4000), 
	"ACCOUNT_NUMBER" VARCHAR2(4000), 
	"ACCOUNT_TYPE" VARCHAR2(4000), 
	"BALANCE_PD_DAY" VARCHAR2(4000), 
	"INTEREST_PD_DAY" VARCHAR2(4000), 
	"FINAL_PD_DAY" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_OVERDUE_ACCOUNT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_OVERDUE_ACCOUNT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_OVERDUE_ACCOUNT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_PREV_POLICY_DECISION" 
   (	"ID" NUMBER, 
	"APPLICATION_ID" VARCHAR2(4000), 
	"PREVIOS_APPLICATION_ID" VARCHAR2(4000), 
	"APPLICANT_ID" VARCHAR2(4000), 
	"PHONE_NUMBER" VARCHAR2(4000), 
	"RESULT_DATE" DATE, 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_PREV_POLICY_DECISION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_PREV_POLICY_DECISION_PK" ON "DE_CBC_RAW_DE"."DE_CBC_PREV_POLICY_DECISION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_PRODUCT" 
   (	"ID" NUMBER, 
	"APPLICATION_ID" VARCHAR2(4000), 
	"APPLICATION_PARENT_CODE" VARCHAR2(4000), 
	"PRODUCT_CLASS" VARCHAR2(4000), 
	"PRODUCT_CODE" VARCHAR2(4000), 
	"PRODUCT_CATEGORY" VARCHAR2(4000), 
	"REGULATION_CODE" VARCHAR2(4000), 
	"PROPOSED_AMOUNT_OR_LIMIT" NUMBER, 
	"LOAN_PROPOSE_MONTH" NUMBER, 
	"APPROVAL_FLOW" VARCHAR2(4000), 
	"LOAN_METHOD" VARCHAR2(4000), 
	"PRODUCT_PACKAGE" VARCHAR2(4000), 
	"LOAN_SECURE" VARCHAR2(4000), 
	"FINAL_DECISION" VARCHAR2(4000), 
	"RECOMMENDED_CREDIT_DECISION" VARCHAR2(4000), 
	"DTI" NUMBER, 
	"MUE" NUMBER, 
	"MIN_PRODUCT_LIMIT" NUMBER, 
	"MAX_PRODUCT_LIMIT" NUMBER, 
	"PRODUCT_FLOW" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	"DRA" NUMBER, 
	 CONSTRAINT "DE_CBC_PRODUCT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_PRODUCT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_PRODUCT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

COMMENT ON COLUMN DE_CBC_RAW_DE.DE_CBC_PRODUCT.DRA IS 'Tiêu chí đánh giá khả năng trả nợ mới (khác DTI)';

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_REFERENCE_INFO" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"REFERENCE_RELATIONSHIP" VARCHAR2(4000), 
	"REFERENCE_NAME" VARCHAR2(4000), 
	"REFERENCE_PHONE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_REFERENCE_INFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_REFERENCE_INFO_PK" ON "DE_CBC_RAW_DE"."DE_CBC_REFERENCE_INFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_RULE_AUDIT_DATA" 
   (	"ID" NUMBER, 
	"APPLICATION_ID" VARCHAR2(4000), 
	"METAPHOR_NAME" VARCHAR2(4000), 
	"RULE_NAME" VARCHAR2(4000), 
	"OUTCOME" VARCHAR2(4000), 
	"TIMESTAMP" DATE, 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_RULE_AUDIT_DATA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_RULE_AUDIT_DATA_PK" ON "DE_CBC_RAW_DE"."DE_CBC_RULE_AUDIT_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_SUB_MODEL_AFFECT_RESULT" 
   (	"ID" NUMBER, 
	"MODEL_INFO_ID" NUMBER, 
	"PRINCIPAL_CODE" VARCHAR2(4000), 
	"SCORE_AFTER_SUB" NUMBER, 
	"RANK_AFTER_SUB" NUMBER, 
	"AFFECT_SCORE_TYPE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_SUB_MODEL_AFFECT_RESULT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_SUB_MODEL_AFFECT_RESULT_PK" ON "DE_CBC_RAW_DE"."DE_CBC_SUB_MODEL_AFFECT_RESULT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_SUB_MODEL_CRITERION_MAP" 
   (	"ID" NUMBER, 
	"MODEL_INFO_ID" NUMBER, 
	"PRINCIPAL_CODE" VARCHAR2(4000), 
	"SUB_SCORE" NUMBER, 
	"SUB_RANK" NUMBER, 
	"SUB_QUESTION_CODE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_SUB_MODEL_CRITERION_MAP_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_SUB_MODEL_CRITERION_MAP_PK" ON "DE_CBC_RAW_DE"."DE_CBC_SUB_MODEL_CRITERION_MAP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_SUB_MODEL_TYPE_REL" 
   (	"ID" NUMBER, 
	"MODEL_INFO_ID" NUMBER, 
	"SUB_MODEL_TYPE_CODE" VARCHAR2(4000), 
	"AFFECT_TYPE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_SUB_MODEL_TYPE_REL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_SUB_MODEL_TYPE_REL_PK" ON "DE_CBC_RAW_DE"."DE_CBC_SUB_MODEL_TYPE_REL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_THIRD_SYSTEM_SCORE" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"SCORE_TYPE" VARCHAR2(4000), 
	"PARTNER_STATUS" VARCHAR2(4000), 
	"PARTNER_CODE" VARCHAR2(4000), 
	"PARTNER_DESC" VARCHAR2(4000), 
	"SCORE" NUMBER, 
	"VERSION" VARCHAR2(4000), 
	"RISKS" VARCHAR2(4000), 
	"RESPONSE_TIME" DATE, 
	"TRACKING_ID" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_THIRD_SYSTEM_SCORE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_THIRD_SYSTEM_SCORE_PK" ON "DE_CBC_RAW_DE"."DE_CBC_THIRD_SYSTEM_SCORE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_UW_CRITERIA" 
   (	"ID" NUMBER, 
	"PREV_POLICY_DECISION_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"GROUP" VARCHAR2(4000), 
	"ACTION" VARCHAR2(4000), 
	"REASON_CODE" VARCHAR2(4000), 
	"REASON_DESCRIPTION" VARCHAR2(4000), 
	"RULE_CATEGORY" VARCHAR2(4000), 
	"APPLICANT_TYPE" VARCHAR2(4000), 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_UW_CRITERIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_UW_CRITERIA_PK" ON "DE_CBC_RAW_DE"."DE_CBC_UW_CRITERIA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."DE_CBC_WAY4" 
   (	"ID" NUMBER, 
	"APPLICANT_REFER_ID" NUMBER, 
	"CODE" NUMBER, 
	"REQUEST_TIMESTAMP" VARCHAR2(4000), 
	"MESSAGE" VARCHAR2(4000), 
	"CONTRACT_NUMBER" VARCHAR2(4000), 
	"CONTRACT_STATUS" VARCHAR2(4000), 
	"CONTRACT_STATUS_CODE" VARCHAR2(4000), 
	"DATE_OPEN" VARCHAR2(4000), 
	"PRODUCT_CODE" VARCHAR2(4000), 
	"CONTRACT_LIMIT" NUMBER, 
	"CREATED_DATE" DATE, 
	 CONSTRAINT "DE_CBC_WAY4_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."DE_CBC_WAY4_PK" ON "DE_CBC_RAW_DE"."DE_CBC_WAY4" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."ODS_APPLICATION" 
   (	"ID" NUMBER, 
	"CIF_NO" VARCHAR2(4000), 
	"MAIN_IDENTIFICATION_NUMBER" VARCHAR2(4000), 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"REQUEST_PAYLOAD" CLOB, 
	"UPDATED_DATETIME" TIMESTAMP (6), 
	 CONSTRAINT "ID_NOT_NULL" CHECK (cif_no is not null OR main_identification_number is not null) ENABLE, 
	 CONSTRAINT "ODS_APPLICATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

 LOB ("REQUEST_PAYLOAD") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."ODS_APPLICATION_PK" ON "DE_CBC_RAW_DE"."ODS_APPLICATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
  CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."SYS_IL0000074191C00005$$" ON "DE_CBC_RAW_DE"."ODS_APPLICATION" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  PARALLEL (DEGREE 0 INSTANCES 0) ;

CREATE TABLE "DE_CBC_RAW_DE"."ODS_APPLICATION_STATE" 
   (	"ID" NUMBER, 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"SOURCE_SYSTEM_ID" VARCHAR2(50) NOT NULL ENABLE, 
	"STATE" VARCHAR2(50) NOT NULL ENABLE, 
	"MESSAGE" VARCHAR2(100), 
	"CREATED_DATETIME" TIMESTAMP (6), 
	"UPDATED_DATETIME" TIMESTAMP (6), 
	 CONSTRAINT "ODS_APPLICATION_STATE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."ODS_APPLICATION_STATE_PK" ON "DE_CBC_RAW_DE"."ODS_APPLICATION_STATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE TABLE "DE_CBC_RAW_DE"."ODS_INTEGRATION_EVENT_LOG" 
   (	"ID" NUMBER, 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(255) NOT NULL ENABLE, 
	"APPLICANT_MAIN_ID" VARCHAR2(4000), 
	"APPLICANT_ID" VARCHAR2(4000), 
	"APPLICANT_TYPE" VARCHAR2(4000), 
	"CALL_TYPE" VARCHAR2(4000), 
	"SYSTEM" VARCHAR2(20) NOT NULL ENABLE, 
	"REQUEST_PAYLOAD" CLOB, 
	"RESPONSE_PAYLOAD" CLOB, 
	"STATUS" VARCHAR2(4000), 
	"START_DATETIME" TIMESTAMP (6), 
	"END_DATETIME" TIMESTAMP (6), 
	"CREATED_DATETIME" TIMESTAMP (6), 
	 CONSTRAINT "ODS_INTEGRATION_EVENT_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

 LOB ("REQUEST_PAYLOAD") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RESPONSE_PAYLOAD") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."ODS_INTEGRATION_EVENT_LOG_PK" ON "DE_CBC_RAW_DE"."ODS_INTEGRATION_EVENT_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
  CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."SYS_IL0000074185C00009$$" ON "DE_CBC_RAW_DE"."ODS_INTEGRATION_EVENT_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."SYS_IL0000074185C00008$$" ON "DE_CBC_RAW_DE"."ODS_INTEGRATION_EVENT_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  PARALLEL (DEGREE 0 INSTANCES 0) ;

CREATE TABLE "DE_CBC_RAW_DE"."ODS_MODEL_EXECUTION_LOG" 
   (	"ID" NUMBER, 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(50) NOT NULL ENABLE, 
	"CUSTOMER_ID" VARCHAR2(4000), 
	"CALL_TYPE" VARCHAR2(4000), 
	"MODEL_NAME" VARCHAR2(4000), 
	"INPUT" CLOB, 
	"OUTPUT" CLOB, 
	"CREATED_DATETIME" TIMESTAMP (6), 
	 CONSTRAINT "ODS_MODEL_EXECUTION_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

 LOB ("INPUT") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("OUTPUT") STORE AS SECUREFILE (
   ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."ODS_MODEL_EXECUTION_LOG_PK" ON "DE_CBC_RAW_DE"."ODS_MODEL_EXECUTION_LOG" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;
  CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."SYS_IL0000074177C00007$$" ON "DE_CBC_RAW_DE"."ODS_MODEL_EXECUTION_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  PARALLEL (DEGREE 0 INSTANCES 0) ;
  CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."SYS_IL0000074177C00006$$" ON "DE_CBC_RAW_DE"."ODS_MODEL_EXECUTION_LOG" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)

  PARALLEL (DEGREE 0 INSTANCES 0) ;

CREATE TABLE "DE_CBC_RAW_DE"."ODS_PREVIOUS_POLICY_DECISION" 
   (	"ID" NUMBER(22,0) NOT NULL ENABLE, 
	"APPLICATION_DE_REF_NUMBER" VARCHAR2(4000), 
	"APPLICANT_IDS" VARCHAR2(4000), 
	"PHONE_NUMBER" VARCHAR2(4000), 
	"RULE_ACTION" VARCHAR2(4000), 
	"REASON_CODE" VARCHAR2(100), 
	"REASON_DESCRIPTION" VARCHAR2(4000), 
	"RULE_CATEGORY" VARCHAR2(4000), 
	"APPLICANT_TYPE" VARCHAR2(100), 
	"RESULT_DATE" TIMESTAMP (6), 
	"CREATE_DATE" TIMESTAMP (6), 
	 CONSTRAINT "ODS_PREVIOUS_POLICY_DECISION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE UNIQUE INDEX "DE_CBC_RAW_DE"."ODS_PREVIOUS_POLICY_DECISION_PK" ON "DE_CBC_RAW_DE"."ODS_PREVIOUS_POLICY_DECISION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
   ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_A05 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_ACC_DETAIL INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_ADDRESS INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_AML INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_APPLICANT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_APPLICANT_VARIABLE INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_APPLICATION_VARIABLE INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_C06 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_CARD_CONTRACT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_CARD_DETAIL INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_CASA_INFO INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_CIC INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_CIC_DERIVED_VARIABLE INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_EXISTS_IDENTIFICATION INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_FRAUD_RULE_BANKING INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_FRAUD_RULE_CAPITAL INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_FRAUD_RULE_RB_APPROVAL INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_IDENTIFICATION INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_INCOME_DETAIL INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_LEAD_DETAIL INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_LEAD_MODEL_INFO INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_LOAN_CONTRACT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_LOAN_DETAIL INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_MODEL_CIC INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_MODEL_CIC_DERIVED_VARIABLE INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_MODEL_INFO INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_MODEL_INTERNAL_DATA INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_MODEL_OUTPUT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_MODEL_RESULT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_MODEL_SCORING_CONSTANT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_MODEL_TYPE_QUES_GROUP INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_MODEL_VARIABLE INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_OD_CONTRACT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_OD_DETAIL INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_OFFER INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_OPRISK INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_OVERDUE_ACCOUNT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_PREV_POLICY_DECISION INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_PRODUCT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_REFERENCE_INFO INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_RULE_AUDIT_DATA INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_SUB_MODEL_AFFECT_RESULT INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_SUB_MODEL_CRITERION_MAP INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_SUB_MODEL_TYPE_REL INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_THIRD_SYSTEM_SCORE INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_UW_CRITERIA INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE DE_CBC_RAW_DE.SEQ_DE_CBC_WAY4 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999 NOCYCLE CACHE 20 NOORDER ;