-------------------DE_CBC_A05----------------------
CREATE TABLE DE_CBC_A05 (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    RESPONSE_CODE     VARCHAR2(4000),
    RESPONSE_MESSAGE  VARCHAR2(4000),
    ACCOUNT_NUMBER    VARCHAR2(4000),
    ACCOUNT_NAME      VARCHAR2(4000),
    RISK_LEVEL        VARCHAR2(4000),
    MESSAGE           VARCHAR2(4000),
    REQUEST_ID        VARCHAR2(4000),
    CREATED_DATE      DATE,

    CONSTRAINT DE_CBC_A05_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DE_CBC_A05
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_ACC_DETAIL----------------------
CREATE TABLE DE_CBC_ACC_DETAIL (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    CIF_NUMBER         VARCHAR2(4000),
    VAR_NAME           VARCHAR2(4000),
    VAR_VALUE          VARCHAR2(4000),
    ACC_TYPE           VARCHAR2(4000),
    CREATED_DATE       DATE,

    CONSTRAINT DE_CBC_ACC_DETAIL_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_ACC_DETAIL
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_ADDRESS----------------------
CREATE TABLE DE_CBC_ADDRESS (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    ADDRESS_TYPE       VARCHAR2(4000),
    PROVINCE_CODE      VARCHAR2(4000),
    PROVINCE_NAME      VARCHAR2(4000),
    DISTRICT_CODE      VARCHAR2(4000),
    DISTRICT_NAME      VARCHAR2(4000),
    STREET             VARCHAR2(4000),
    WARD_CODE          VARCHAR2(4000),
    WARD_NAME          VARCHAR2(4000),
    CREATED_DATE       DATE,

    CONSTRAINT DE_CBC_ADDRESS_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DE_CBC_ADDRESS
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_AML----------------------
CREATE TABLE DE_CBC_AML (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    AML_LIST_NAME      VARCHAR2(4000),
    CREATED_DATE       DATE,

    CONSTRAINT DE_CBC_AML_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_AML
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_APPLICANT----------------------
CREATE TABLE DE_CBC_APPLICANT (
    ID NUMBER NOT NULL,
    APPLICATION_ID                     VARCHAR2(4000),
    APPLICANT_TYPE                     VARCHAR2(4000),
    CUSTOMER_SEGMENT                   VARCHAR2(4000),
    APPLICANT_NAME                     VARCHAR2(4000),
    CIF_NUMBER                         VARCHAR2(4000),
    DOB                                VARCHAR2(4000),
    AGE                                NUMBER,
    GENDER                             VARCHAR2(4000),
    NATIONALITY                        VARCHAR2(4000),
    PHONE                              VARCHAR2(4000),
    EMAIL                              VARCHAR2(4000),
    MARITAL_STATUS                     VARCHAR2(4000),
    JOB                                 VARCHAR2(4000),
    AGENCY_POSITION                     VARCHAR2(4000),
    OVERALL_SCORE                      NUMBER,
    RECORDED_INCOME                    NUMBER,
    INCOME_FROM_MODEL                  NUMBER,
    MODEL_ACCEPT_BEFORE_MODEL_FLOW     VARCHAR2(4000),
    FLAG_ACCEPT_MODEL                  VARCHAR2(4000),
    MODEL_FLOW_POINT                   VARCHAR2(4000),
    OVERALL_MODEL_RATING               VARCHAR2(4000),
    INCOME_METHOD                      VARCHAR2(4000),
    CONVERSION_METHOD                  VARCHAR2(4000),
    CREATED_DATE                       DATE,
    IS_NTB                              VARCHAR2(4000),
    IS_SECURE                           VARCHAR2(4000),
    CONSTRAINT DE_CBC_APPLICANT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_APPLICANT
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_APPLICANT_VARIABLE----------------------
CREATE TABLE DE_CBC_APPLICANT_VARIABLE (
    ID NUMBER NOT NULL ,
    APPLICANT_REFER_ID NUMBER,
    VAR_NAME VARCHAR2(4000),
    VAR_VALUE VARCHAR2(4000),
    VAR_TYPE VARCHAR2(4000),
    VAR_GROUP VARCHAR2(4000),
    CREATED_DATE DATE,
    CONSTRAINT DE_CBC_APPLICANT_VARIABLE_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_APPLICANT_VARIABLE
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_APPLICATION----------------------
CREATE TABLE DE_CBC_APPLICATION (
    APPLICATION_ID            VARCHAR2(4000) NOT NULL,
    APPLICATION_CODE_MBA      VARCHAR2(4000),
    SOURCE                    VARCHAR2(4000),
    VERSION                   NUMBER,
    APPLICATION_CODE_BPM      VARCHAR2(4000),
    APPLICATION_FLOW          VARCHAR2(4000),
    APPLICATION_CREATE_TIME   VARCHAR2(4000),
    APPLICATION_SALE_ID       VARCHAR2(4000),
    RECOMMENDED_DECISION      VARCHAR2(4000),
    CREATED_DATE              DATE,

    CONSTRAINT PK_DE_CBC_APPLICATION PRIMARY KEY (APPLICATION_ID)
);

CREATE SEQUENCE SEQ_DE_CBC_APPLICATION
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_APPLICATION_VARIABLE----------------------
CREATE TABLE DE_CBC_APPLICATION_VARIABLE (
     ID NUMBER NOT NULL ,
     APPLICATION_ID VARCHAR2(4000),
     PRODUCT_ID NUMBER,
     VAR_NAME VARCHAR2(4000),
     VAR_VALUE VARCHAR2(4000),
     VAR_TYPE VARCHAR2(4000),
     VAR_GROUP VARCHAR2(4000),
     CREATED_DATE DATE,
     CONSTRAINT DE_CBC_APPLICATION_VARIABLE_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_APPLICATION_VARIABLE
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_C06----------------------
CREATE TABLE DE_CBC_C06 (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    CARD_NO            VARCHAR2(4000),
    STATUS             VARCHAR2(4000),
    MESSAGE            VARCHAR2(4000),
    OLD_ID_CARD_NO     VARCHAR2(4000),
    ADDRESS            VARCHAR2(4000),
    PLACE_OF_ORIGIN    VARCHAR2(4000),
    MOTHER_NAME        VARCHAR2(4000),
    SPOUSE_NAME        VARCHAR2(4000),
    FATHER_NAME        VARCHAR2(4000),
    CREATED_DATE       DATE,

    CONSTRAINT DE_CBC_C06_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_C06
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_CARD_CONTRACT----------------------
CREATE TABLE DE_CBC_CARD_CONTRACT (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    SOURCE_SYSTEM      VARCHAR2(4000),
    CONTRACT_ID        VARCHAR2(4000),
    CONTRACT_NUMBER    VARCHAR2(4000),
    AUTH_LIMIT_AMOUNT  NUMBER,
    GTTT               VARCHAR2(4000),
    APPLICATION_CODE   VARCHAR2(4000),
    SECURED            VARCHAR2(4000),
    COLLATCODE_FLAG    VARCHAR2(4000),
    APPROVAL_TIME      DATE,
    CREATED_DATE       DATE,

    CONSTRAINT DE_CBC_CARD_CONTRACT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_CARD_CONTRACT
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_CARD_DETAIL----------------------
CREATE TABLE DE_CBC_CARD_DETAIL (
    ID NUMBER NOT NULL,
    CARD_CONTRACT_ID NUMBER,
    CIF_NO           VARCHAR2(4000),
    STATUS           VARCHAR2(4000),
    PRODUCT_CODE     VARCHAR2(4000),
    PRODUCT_INFO     NUMBER,
    SOURCE_SYSTEM    VARCHAR2(4000),
    CREATED_DATE       DATE,

    CONSTRAINT DE_CBC_CARD_DETAIL_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DE_CBC_CARD_DETAIL
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_CASA_INFO----------------------
CREATE TABLE DE_CBC_CASA_INFO (
      ID NUMBER NOT NULL,
      LEAD_REFER_ID NUMBER,
      INCOME_POLICY_CODE    VARCHAR2(4000),
      SALARY_MSB_01     NUMBER,
      SALARY_MSB_02     NUMBER,
      SALARY_MSB_03     NUMBER,
      CASA_BALANCE_01   NUMBER,
      CASA_BALANCE_02   NUMBER,
      CASA_BALANCE_03   NUMBER,
      CREATED_DATE       DATE,

      CONSTRAINT DE_CBC_CASA_INFO_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_CASA_INFO
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_CIC----------------------
CREATE TABLE DE_CBC_CIC (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    CLIENT_QUESTION_ID VARCHAR2(4000),
    STATUS VARCHAR2(4000),
    REPORT_DATE DATE,
    TRANSACTION_TIME DATE,
    CODE_MESSAGE VARCHAR2(4000),
    TAX_NO VARCHAR2(4000),
    BUSINESS_REGISTRATION_NUMBER VARCHAR2(4000),
    CUSTOMER_IDENTIFICATION_NUMBER VARCHAR2(4000),
    CIC_CODE VARCHAR2(4000),
    ADDRESS VARCHAR2(4000),
    CUSTOMER_NAME VARCHAR2(4000),
    PHONE_NUMBER VARCHAR2(4000),
    DIRECTOR_NAME VARCHAR2(4000),
    FINANCIAL_YEAR VARCHAR2(4000),
    NOTE VARCHAR2(4000),
    "GROUP" VARCHAR2(4000),
    CREATED_DATE DATE,
    CONSTRAINT DE_CBC_CIC_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_CIC
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_CIC_DERIVED_VARIABLE----------------------
CREATE TABLE DE_CBC_CIC_DERIVED_VARIABLE (
     ID            NUMBER NOT NULL,
     CIC_ID        NUMBER,
     VAR_NAME      VARCHAR2(4000),
     VAR_VALUE     VARCHAR2(4000),
     "GROUP"         VARCHAR2(4000),
     CREATED_DATE  DATE,

     CONSTRAINT DE_CBC_CIC_DERIVED_VARIABLE_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_CIC_DERIVED_VARIABLE
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_ERROR----------------------
CREATE TABLE DE_CBC_ERROR (
    APPLICATION_ID VARCHAR2(4000),
    ERROR_CODE VARCHAR2(4000),
    ERROR_DESCRIPTION CLOB,
    SOURCE VARCHAR2(4000),
    DATETIME VARCHAR2(4000),
    TRACE CLOB,
    CREATED_DATE DATE
);

CREATE SEQUENCE SEQ_DE_CBC_ERROR
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_EXISTS_IDENTIFICATION----------------------
CREATE TABLE DE_CBC_EXISTS_IDENTIFICATION (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    CIF_NUMBER       VARCHAR2(4000),
    GTTT             VARCHAR2(4000),
    IDENTIFICATION_TYPE   VARCHAR2(4000),
    AML_LIST_NAME    VARCHAR2(4000),
    ACCOUNT_NO       VARCHAR2(4000),
    CARD_NO          VARCHAR2(4000),
    MOTHER_NAME      VARCHAR2(4000),
    SPOUSE_NAME      VARCHAR2(4000),
    OPEN_DATE        DATE,
    CREATED_DATE     DATE,

    CONSTRAINT DE_CBC_EXISTS_IDENTIFICATION_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_DE_CBC_EXISTS_IDENTIFICATION
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_FRAUD_RULE_BANKING----------------------
CREATE TABLE DE_CBC_FRAUD_RULE_BANKING (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    CIF                VARCHAR2(4000),
    NAME               VARCHAR2(4000),
    NAME_CLN           VARCHAR2(4000),
    CONTACT_TYPE       VARCHAR2(4000),
    CONTACT_INFO       VARCHAR2(4000),
    CONTACT_INFO_CLN   VARCHAR2(4000),
    SOURCE_SYSTEM      VARCHAR2(4000),
    CREATED_DATE       DATE,
    CONSTRAINT DE_CBC_FRAUD_RULE_BANKING_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_FRAUD_RULE_BANKING
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_FRAUD_RULE_CAPITAL----------------------
CREATE TABLE DE_CBC_FRAUD_RULE_CAPITAL (
    ID                        NUMBER NOT NULL,
    APPLICANT_REFER_ID        NUMBER,
    MSB_EQUITY                VARCHAR2(4000),
    EFFECTIVE_DATE            VARCHAR2(4000),
    STATUS                    VARCHAR2(4000),
    CREATED_DATE              DATE,
    CONSTRAINT DE_CBC_FRAUD_RULE_CAPITAL_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_FRAUD_RULE_CAPITAL
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_FRAUD_RULE_RB_APPROVAL----------------------
CREATE TABLE DE_CBC_FRAUD_RULE_RB_APPROVAL (
    ID                        NUMBER NOT NULL,
    APPLICANT_REFER_ID        NUMBER,
    CIF                     VARCHAR2(4000),
    APPLICATION_CODE        VARCHAR2(4000),
    NAME                    VARCHAR2(4000),
    NAME_CLN                VARCHAR2(4000),
    PHONE                   VARCHAR2(4000),
    PHONE_CLN               VARCHAR2(4000),
    RELATION_CODE           VARCHAR2(4000),
    CREATED_DATE            DATE,
    CONSTRAINT DE_CBC_FRAUD_RULE_RB_APPROVAL_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DE_CBC_FRAUD_RULE_RB_APPROVAL
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_IDENTIFICATION----------------------
CREATE TABLE DE_CBC_IDENTIFICATION (
    ID                        NUMBER NOT NULL,
    APPLICANT_REFER_ID        NUMBER,
    IS_MAIN_IDENTIFICATION    VARCHAR2(4000),
    IDENTIFICATION_NUMBER   VARCHAR2(4000),
    PLACE_OF_ISSUE          VARCHAR2(4000),
    DATE_OF_ISSUE             DATE,
    DATE_OF_EXPIRE            DATE,
    IDENTIFICATION_TYPE_MAIN  VARCHAR2(4000),
    CREATED_DATE            DATE,
    CONSTRAINT DE_CBC_IDENTIFICATION_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_IDENTIFICATION
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_INCOME_DETAIL----------------------
CREATE TABLE DE_CBC_INCOME_DETAIL (
    ID                        NUMBER NOT NULL,
    APPLICANT_REFER_ID        NUMBER,
    INCOME_MONTH   NUMBER,
    INCOME_TYPE    VARCHAR2(4000),
    CREATED_DATE   DATE,
    CONSTRAINT DE_CBC_INCOME_DETAIL_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_INCOME_DETAIL
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_LEAD_DETAIL----------------------
CREATE TABLE DE_CBC_LEAD_DETAIL (
    ID                        NUMBER NOT NULL,
    APPLICANT_REFER_ID        NUMBER,
    LEAD_ID             VARCHAR2(4000),
    LEAD_NAME           VARCHAR2(4000),
    LEAD_TYPE           VARCHAR2(4000),
    LEAD_LIMIT          NUMBER,
    CREDIT_CARD_LIMIT   NUMBER,
    EFFECTIVE_DATE      DATE,
    EXPERY_DATE      DATE,
    CREATED_DATE        DATE,
    CONSTRAINT DE_CBC_LEAD_DETAIL_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_LEAD_DETAIL
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------
-------------------DE_CBC_LEAD_MODEL_INFO----------------------
CREATE TABLE DE_CBC_LEAD_MODEL_INFO (
    ID                NUMBER        NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    RANK              VARCHAR2(4000),
    MODEL_TYPE_CODE   VARCHAR2(4000),
    MODEL_INFO_CODE   VARCHAR2(4000),
    PRODUCT_CLASS     VARCHAR2(4000),
    RANK_ORDER        NUMBER,
    EFFECTIVE_DATE    DATE,
    EXPIRE_DATE       DATE,
    CUST_ID           VARCHAR2(4000),
    CIF_NUMBER        VARCHAR2(4000),
    CREATED_DATE      DATE,
    RECOMMENDATION    VARCHAR2(4000),
    FINAL_SCORE       NUMBER,
    MODEL_GROUP_NAME  VARCHAR2(4000),
    LOAN_METHOD       VARCHAR2(4000),
    PRODUCT_CATEGORY  VARCHAR2(4000),
    TYPE_OF_MODEL     VARCHAR2(4000),
    SCORING_DATE      DATE,
    CONSTRAINT DE_CBC_LEAD_MODEL_INFO_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DE_CBC_LEAD_MODEL_INFO
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_LOAN_CONTRACT----------------------
CREATE TABLE DE_CBC_LOAN_CONTRACT (
    ID                  NUMBER        NOT NULL,
    APPLICANT_REFER_ID  NUMBER,
    CONTRACT_ID         VARCHAR2(4000),
    CIF                 VARCHAR2(4000),
    ACF_STATUS          VARCHAR2(4000),
    EXPIRY_DATE         DATE,
    AMOUNT_APPROVED     NUMBER,
    APPROVAL_TIME       DATE,
    SECURED             VARCHAR2(4000),
    COLLATCODE_FLAG     VARCHAR2(4000),
    REVOL_NON_REVOL     DATE,
    GTTT                VARCHAR2(4000),
    SOURCE_SYSTEM       VARCHAR2(4000),
    SCORING_DATE        DATE,
    CREATED_DATE        DATE,
    CONSTRAINT DE_CBC_LOAN_CONTRACT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_LOAN_CONTRACT
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_LOAN_DETAIL----------------------
CREATE TABLE DE_CBC_LOAN_DETAIL (
    ID                  NUMBER        NOT NULL,
    LOAN_CONTRACT_ID    NUMBER,
    CIF_NO              VARCHAR2(4000),
    LOAN_ACCOUNT_NUMBER VARCHAR2(4000),
    PRODUCT_CODE        VARCHAR2(4000),
    PRODUCT_INFO        DATE,
    PAYMENT_CODE        NUMBER,
    AMOUNT              NUMBER,
    OUTSTANDING_BALANCE NUMBER,
    PAYMENT_AMT         NUMBER,
    REMAINING_MONTHS    NUMBER,
    LIMIT_TERM          NUMBER,
    DISBURSED_AMT       NUMBER,
    STATUS              VARCHAR2(4000),
    SOURCE_SYSTEM       VARCHAR2(4000),
    CREATED_DATE        DATE,
    CONSTRAINT DE_CBC_LOAN_DETAIL_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_LOAN_DETAIL
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_MODEL_CIC----------------------
CREATE TABLE DE_CBC_MODEL_CIC (
    ID                  NUMBER        NOT NULL,
    APPLICANT_REFER_ID  NUMBER,
    CLIENT_QUESTION_ID  VARCHAR2(4000),
    STATUS              VARCHAR2(4000),
    REPORT_DATE         DATE,
    TRANSACTION_TIME    DATE,
    CODE_MESSAGE        VARCHAR2(4000),
    TAX_NO              VARCHAR2(4000),
    BUSINESS_REGISTRATION_NUMBER        VARCHAR2(4000),
    CUSTOMER_IDENTIFICATION_NUMBER      VARCHAR2(4000),
    CIC_CODE            VARCHAR2(4000),
    ADDRESS             VARCHAR2(4000),
    CUSTOMER_NAME       VARCHAR2(4000),
    PHONE_NUMBER        VARCHAR2(4000),
    DIRECTOR_NAME       VARCHAR2(4000),
    FINANCIAL_YEAR      VARCHAR2(4000),
    NOTE                VARCHAR2(4000),
    "GROUP"               VARCHAR2(4000),
    CREATED_DATE        DATE,
    CONSTRAINT DE_CBC_MODEL_CIC_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_MODEL_CIC
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_MODEL_CIC_DERIVED_VARIABLE----------------------
CREATE TABLE DE_CBC_MODEL_CIC_DERIVED_VARIABLE (
    ID                  NUMBER        NOT NULL,
    CIC_ID              NUMBER,
    VAR_NAME            VARCHAR2(4000),
    VAR_VALUE           VARCHAR2(4000),
    "GROUP"               VARCHAR2(4000),
    CREATED_DATE        DATE,
    CONSTRAINT DE_CBC_MODEL_CIC_DERIVED_VARIABLE_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_MODEL_CIC_DERIVED_VARIABLE
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_MODEL_INFO----------------------
CREATE TABLE DE_CBC_MODEL_INFO (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    CUST_ID VARCHAR2(4000),
    CIF_NUMBER VARCHAR2(4000),
    MODEL_INFO_CODE VARCHAR2(4000),
    MODEL_TYPE_CODE VARCHAR2(4000),
    TYPE_OF_MODEL VARCHAR2(4000),
    TYPE_OF_SEGMENT VARCHAR2(4000),
    SEGMENT_RESULT VARCHAR2(4000),
    ML_FLG VARCHAR2(4000),
    IS_MODEL_AUTO VARCHAR2(4000),
    SUB_MODEL_TYPE VARCHAR2(4000),
    OVERRIDE_TOLERANCE_SUB VARCHAR2(4000),
    IS_SEGMENT_MODEL VARCHAR2(4000),
    MODEL_CATEGORY VARCHAR2(4000),
    MODEL_TYPE_SCORE_DIRECTION VARCHAR2(4000),
    MODEL_SEQUENCE_NO NUMBER,
    CREATED_DATE DATE,
    APPLICANT_ID VARCHAR2(4000),
    FLAG_EXECUTE_STATUS VARCHAR2(4000),
    MODEL_GROUP_NAME VARCHAR2(4000),
    LOAN_METHOD VARCHAR2(4000),
    PRODUCT_CATEGORY VARCHAR2(4000),
    LOAN_METHOD_REQUEST VARCHAR2(4000),
    PRODUCT_CATEGORY_REQUEST VARCHAR2(4000),
    IS_NEXT_MODEL VARCHAR2(4000),
    CONSTRAINT DE_CBC_MODEL_INFO_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_MODEL_INFO
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_MODEL_INTERNAL_DATA----------------------
CREATE TABLE DE_CBC_MODEL_INTERNAL_DATA (
    ID NUMBER NOT NULL,
    APPLICANT_REFER_ID NUMBER,
    CIF_NUMBER VARCHAR2(4000),
    VAR_NAME VARCHAR2(4000),
    VAR_VALUE VARCHAR2(4000),
    ACC_TYPE VARCHAR2(4000),
    CREATED_DATE DATE,
    CONSTRAINT DE_CBC_MODEL_INTERNAL_DATA_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_MODEL_INTERNAL_DATA
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_MODEL_OUTPUT----------------------
CREATE TABLE DE_CBC_MODEL_OUTPUT (
     ID                  NUMBER        NOT NULL,
     APPLICANT_REFER_ID  NUMBER,
     RANK                VARCHAR2(4000),
     MODEL_TYPE_CODE     VARCHAR2(4000),
     PRODUCT_CATEGORY    VARCHAR2(4000),
     RANK_ORDER          VARCHAR2(4000),
     MODEL_GROUP_NAME      VARCHAR2(4000),
     TYPE_OF_MODEL         VARCHAR2(4000),
     LOAN_METHOD           VARCHAR2(4000),
     RECOMMENDATION        VARCHAR2(4000),
     FINAL_SCORE           NUMBER,
     SCORING_DATE          DATE,
     SPECIALIZED_BANK      VARCHAR2(4000),
     CUST_ID               VARCHAR2(4000),
     CIF_NUMBER            VARCHAR2(4000),
     IS_MODEL_SELECTED     VARCHAR2(4000),
	 MODEL_INFO_CODE       VARCHAR2(4000),
     CREATED_DATE          DATE,
     CONSTRAINT DE_CBC_MODEL_OUTPUT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_MODEL_OUTPUT
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_MODEL_RESULT----------------------
CREATE TABLE DE_CBC_MODEL_RESULT (
     ID                  NUMBER        NOT NULL,
     MODEL_INFO_ID  NUMBER,
     MODEL_TYPE_SCORE_DIRECTION                VARCHAR2(4000),
     OVERRIDE_VALUE     NUMBER,
     SPECIALIZED_BANK    VARCHAR2(4000),
     STANDARDISED_SCORE          NUMBER,
     OVERRIDE_LEVEL      VARCHAR2(4000),
     SCORE         NUMBER,
     SCORE_PD           NUMBER,
     UNCALIBRATED_PD        NUMBER,
     CALIBRATED_PD           NUMBER,
     FINAL_SCORE          NUMBER,
     RANK      VARCHAR2(4000),
     RANK_ORDER               NUMBER,
     RECOMMENDATION            VARCHAR2(4000),
     RESULT_STATUS_CODE     VARCHAR2(4000),
     IS_MODEL_SELECTED     VARCHAR2(4000),
     IS_OVERRIDE     VARCHAR2(4000),
     IS_TOLERRANCE     VARCHAR2(4000),
     IS_SUB_AFFECT     VARCHAR2(4000),
     EXPIRY_DATE          DATE,
     SCORING_DATE          DATE,
     CREATED_DATE          DATE,
     STEP_FINAL          NUMBER,
     PRODUCT_CLASS          VARCHAR2(4000),
     CONSTRAINT DE_CBC_MODEL_RESULT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_MODEL_RESULT
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_MODEL_SCORING_CONSTANT----------------------
CREATE TABLE DE_CBC_MODEL_SCORING_CONSTANT (
    ID             NUMBER        NOT NULL,
    MODEL_INFO_ID  NUMBER,
    CONSTANT_CODE  VARCHAR2(4000),
    CONSTANT_VALUE  NUMBER,
    CONSTANT_ORDER  NUMBER,
    STANDARDISED_SCORE          NUMBER,
    OVERRIDE_LEVEL      VARCHAR2(4000),
    SCORE         NUMBER,
    SCORE_PD           NUMBER,
    UNCALIBRATED_PD        NUMBER,
    CALIBRATED_PD           NUMBER,
    FINAL_SCORE          NUMBER,
    RANK      VARCHAR2(4000),
    RANK_ORDER               NUMBER,
    RECOMMENDATION            VARCHAR2(4000),
    RESULT_STATUS_CODE     VARCHAR2(4000),
    IS_MODEL_SELECTED     VARCHAR2(4000),
    IS_OVERRIDE     VARCHAR2(4000),
    IS_TOLERRANCE     VARCHAR2(4000),
    IS_SUB_AFFECT     VARCHAR2(4000),
    EXPIRY_DATE          DATE,
    SCORING_DATE          DATE,
    CREATED_DATE          DATE,
    STEP_FINAL          NUMBER,
    PRODUCT_CLASS          VARCHAR2(4000),
    CONSTRAINT DE_CBC_MODEL_SCORING_CONSTANT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_MODEL_SCORING_CONSTANT
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_MODEL_TYPE_QUES_GROUP----------------------
CREATE TABLE DE_CBC_MODEL_TYPE_QUES_GROUP (
    ID             NUMBER        NOT NULL,
    MODEL_INFO_ID  NUMBER,
    CODE  VARCHAR2(4000),
    NAME  VARCHAR2(4000),
    WEIGHT  NUMBER,
    STD     NUMBER,
    MEAN      NUMBER,
    SCORE         NUMBER,
    STANDARDIZE_SCORE           NUMBER,
    CREATED_DATE          DATE,
    STEP_FINAL          NUMBER,
    PRODUCT_CLASS          VARCHAR2(4000),
    CONSTRAINT DE_CBC_MODEL_TYPE_QUES_GROUP_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_MODEL_TYPE_QUES_GROUP
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_MODEL_VARIABLE----------------------
CREATE TABLE DE_CBC_MODEL_VARIABLE (
    ID                   NUMBER NOT NULL,
    MODEL_INFO_ID        NUMBER,
    QUESTION_CODE        VARCHAR2(4000),
    ANS_DATA_TYPE        VARCHAR2(4000),
    ANSWER_VALUE         VARCHAR2(4000),
    MODEL_TYPE_CODE      VARCHAR2(4000),
    DATE_ANSWER          DATE,
    MODEL_TYPE_QUES_CODE VARCHAR2(4000),
    CALCULATE_LEVEL      NUMBER,
    MODEL_TYPE_QUES_GROUP VARCHAR2(4000),
    WEIGHT               NUMBER,
    MEAN                 NUMBER,
    STD                  NUMBER,
    IS_SUB_ACCOMPANY     VARCHAR2(4000),
    IS_TOLERANCE         VARCHAR2(4000),
    TOLERANCE_UNIT       VARCHAR2(4000),
    TOLERANCE_VALUE      NUMBER,
    IS_OVERRIDE          VARCHAR2(4000),
    OVERRIDE_TYPE        VARCHAR2(4000),
    OVERRIDE_VALUE       NUMBER,
    ML_QUESTION_CODE     VARCHAR2(4000),
    NUMERIC_ANSWER       NUMBER,
    BOOLEAN_ANSWER       VARCHAR2(4000),
    STRING_ANSWER        VARCHAR2(4000),
    PARTIAL_SCORE        NUMBER,
    STANDARDIZE_SCORE    NUMBER,
    REASON_CODE          VARCHAR2(4000),
    ANSWER_ORDER         NUMBER,
    SCORE_ORDER         NUMBER,
    IS_TOLERANCE_APPLIED          VARCHAR2(4000),
    IS_OVERRIDE_APPLIED          VARCHAR2(4000),
    RANK_ORDER          NUMBER,
    CREATED_DATE          DATE,
    OVERRIDE_DIRECTION          VARCHAR2(4000),
    INT_OR_REAL_ANSWER          NUMBER,
    OVERRIDEN_RANK          NUMBER,
    CONSTRAINT DE_CBC_MODEL_VARIABLE_PK PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DE_CBC_MODEL_VARIABLE
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_OD_CONTRACT----------------------
CREATE TABLE DE_CBC_OD_CONTRACT (
    ID                      NUMBER NOT NULL,
    APPLICANT_REFER_ID      NUMBER,
    CONTRACT_ID             VARCHAR2(4000),
    SOURCE_SYSTEM           VARCHAR2(4000),
    CIF_NO                  VARCHAR2(4000),
    OVERDRAFT_LIMIT         NUMBER,
    SECURED                 VARCHAR2(4000),
    COLLATCODE_FLAG         VARCHAR2(4000),
    OVERDRAFT_EXPIRY_DATE   DATE,
    GTTT                    VARCHAR2(4000),
    APPLICATION_CODE        VARCHAR2(4000),
    APPROVAL_TIME           DATE,
    CREATED_DATE            DATE,

    CONSTRAINT DE_CBC_OD_CONTRACT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_OD_CONTRACT
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_OD_DETAIL----------------------
CREATE TABLE DE_CBC_OD_DETAIL (
    ID                              NUMBER NOT NULL,
    OD_CONTRACT_ID                  NUMBER,
    CIF_NO                          VARCHAR2(4000),
    OVERDRAFT_ACCOUNT               VARCHAR2(4000),
    OVERDRAFT_OUTSTANDING_BALANCE   NUMBER,
    PRODUCT_CODE                    VARCHAR2(4000),
    PRODUCT_INFO                    VARCHAR2(4000),
    STATUS                          VARCHAR2(4000),
    SOURCE_SYSTEM                   VARCHAR2(4000),
    CREATED_DATE                    DATE,

    CONSTRAINT DE_CBC_OD_DETAIL_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_OD_DETAIL
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_OFFER----------------------
CREATE TABLE DE_CBC_OFFER (
    ID                              NUMBER NOT NULL,
    PRODUCT_ID                      NUMBER,
    APPROVED_CREDIT_OR_LOAN_LIMIT   NUMBER,
    APPROVAL_TERM                   NUMBER,
    APPROVAL_VALIDITY               DATE,
    APPROVAL_TIME                   DATE,
    INTEREST_RATE                   NUMBER,
    CREATED_DATE                    DATE,
    CONSTRAINT DE_CBC_OFFER_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_OFFER
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_OPRISK----------------------
CREATE TABLE DE_CBC_OPRISK (
    ID_OPRISK            NUMBER,
    APPLICANT_REFER_ID   NUMBER,
    ADDRESS              VARCHAR2(4000),
    BRANCH_INPUT         VARCHAR2(4000),
    CUS_ID               VARCHAR2(4000),
    DATE_EX              DATE,
    DATE_INPUT           DATE,
    DOB                  DATE,
    DSCN                 VARCHAR2(4000),
    DTCN                 VARCHAR2(4000),
    ERROR_MESS           VARCHAR2(4000),
    ID                   VARCHAR2(4000) NOT NULL,
    INPUT_USER           VARCHAR2(4000),
    NAME                 VARCHAR2(4000),
    RECORD_ID            VARCHAR2(4000),
    RESULT               VARCHAR2(4000),
    VERSION              VARCHAR2(4000),
    CREATED_DATE         DATE,

    CONSTRAINT DE_CBC_OPRISK_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_OPRISK
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_OVERDUE_ACCOUNT----------------------
CREATE TABLE DE_CBC_OVERDUE_ACCOUNT (
    ID                  NUMBER NOT NULL,
    APPLICANT_REFER_ID  NUMBER,
    CIF                 VARCHAR2(4000),
    ACCOUNT_NUMBER      VARCHAR2(4000),
    ACCOUNT_TYPE        VARCHAR2(4000),
    BALANCE_PD_DAY      VARCHAR2(4000),
    INTEREST_PD_DAY     VARCHAR2(4000),
    FINAL_PD_DAY        VARCHAR2(4000),
    CREATED_DATE        DATE,

    CONSTRAINT DE_CBC_OVERDUE_ACCOUNT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_OVERDUE_ACCOUNT
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_PREV_POLICY_DECISION----------------------
CREATE TABLE DE_CBC_PREV_POLICY_DECISION (
     ID                  NUMBER NOT NULL,
     APPLICATION_ID      VARCHAR2(4000),
     PREVIOS_APPLICATION_ID  VARCHAR2(4000),
     APPLICANT_ID        VARCHAR2(4000),
     PHONE_NUMBER        VARCHAR2(4000),
     RESULT_DATE         DATE,
     CREATED_DATE        DATE,
     CONSTRAINT DE_CBC_PREV_POLICY_DECISION_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_PREV_POLICY_DECISION
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_PRODUCT----------------------
CREATE TABLE DE_CBC_PRODUCT (
    ID                          NUMBER NOT NULL,
    APPLICATION_ID              VARCHAR2(4000),
    APPLICATION_PARENT_CODE     VARCHAR2(4000),
    PRODUCT_CLASS               VARCHAR2(4000),
    PRODUCT_CODE                VARCHAR2(4000),
    PRODUCT_CATEGORY            VARCHAR2(4000),
    REGULATION_CODE             VARCHAR2(4000),
    PROPOSED_AMOUNT_OR_LIMIT    NUMBER,
    LOAN_PROPOSE_MONTH          NUMBER,
    APPROVAL_FLOW               VARCHAR2(4000),
    LOAN_METHOD                 VARCHAR2(4000),
    PRODUCT_PACKAGE             VARCHAR2(4000),
    LOAN_SECURE                 VARCHAR2(4000),
    FINAL_DECISION              VARCHAR2(4000),
    RECOMMENDED_CREDIT_DECISION VARCHAR2(4000),
    DTI                         NUMBER,
    MUE                         NUMBER,
    MIN_PRODUCT_LIMIT           NUMBER,
    MAX_PRODUCT_LIMIT           NUMBER,
    PRODUCT_FLOW                VARCHAR2(4000),
    CREATED_DATE                DATE,
    DRA                         NUMBER,
    CONSTRAINT DE_CBC_PRODUCT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_PRODUCT
    START WITH 1
    INCREMENT BY 1;
	
-----------------------------------------

-------------------DE_CBC_REFERENCE_INFO----------------------
CREATE TABLE DE_CBC_REFERENCE_INFO (
    ID                          NUMBER NOT NULL,
    APPLICANT_REFER_ID          NUMBER,
    REFERENCE_RELATIONSHIP      VARCHAR2(4000),
    REFERENCE_NAME              VARCHAR2(4000),
    REFERENCE_PHONE             VARCHAR2(4000),
    CREATED_DATE                DATE,
    CONSTRAINT DE_CBC_REFERENCE_INFO_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_REFERENCE_INFO
    START WITH 1
    INCREMENT BY 1;	
-----------------------------------------

-------------------DE_CBC_RULE_AUDIT_DATA----------------------
CREATE TABLE DE_CBC_RULE_AUDIT_DATA (
    ID                          NUMBER NOT NULL,
    APPLICATION_ID              VARCHAR2(4000),
    METAPHOR_NAME               VARCHAR2(4000),
    RULE_NAME                   VARCHAR2(4000),
    OUTCOME                     VARCHAR2(4000),
    TIMESTAMP                   DATE,
    CREATED_DATE                DATE,
    CONSTRAINT DE_CBC_RULE_AUDIT_DATA_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_RULE_AUDIT_DATA
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------DE_CBC_SUB_MODEL_AFFECT_RESULT----------------------
CREATE TABLE DE_CBC_SUB_MODEL_AFFECT_RESULT (
    ID                          NUMBER NOT NULL,
    MODEL_INFO_ID               NUMBER,
    PRINCIPAL_CODE              VARCHAR2(4000),
    SCORE_AFTER_SUB             NUMBER,
    RANK_AFTER_SUB              NUMBER,
    AFFECT_SCORE_TYPE           VARCHAR2(4000),
    CREATED_DATE                DATE,
    CONSTRAINT DE_CBC_SUB_MODEL_AFFECT_RESULT_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_SUB_MODEL_AFFECT_RESULT
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------DE_CBC_SUB_MODEL_CRITERION_MAP----------------------
CREATE TABLE DE_CBC_SUB_MODEL_CRITERION_MAP (
    ID                          NUMBER NOT NULL,
    MODEL_INFO_ID               NUMBER,
    PRINCIPAL_CODE              VARCHAR2(4000),
    SUB_SCORE                   NUMBER,
    SUB_RANK                    NUMBER,
    SUB_QUESTION_CODE           VARCHAR2(4000),
    CREATED_DATE                DATE,
    CONSTRAINT DE_CBC_SUB_MODEL_CRITERION_MAP_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_SUB_MODEL_CRITERION_MAP
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------DE_CBC_SUB_MODEL_TYPE_REL----------------------
CREATE TABLE DE_CBC_SUB_MODEL_TYPE_REL (
    ID                          NUMBER NOT NULL,
    MODEL_INFO_ID               NUMBER,
    SUB_MODEL_TYPE_CODE         VARCHAR2(4000),
    AFFECT_TYPE                 VARCHAR2(4000),
    CREATED_DATE                DATE,
    CONSTRAINT DE_CBC_SUB_MODEL_TYPE_REL_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_SUB_MODEL_TYPE_REL
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------DE_CBC_THIRD_SYSTEM_SCORE----------------------
CREATE TABLE DE_CBC_THIRD_SYSTEM_SCORE (
    ID                  NUMBER NOT NULL,
    APPLICANT_REFER_ID  NUMBER,
    SCORE_TYPE          VARCHAR2(4000),
    PARTNER_STATUS      VARCHAR2(4000),
    PARTNER_CODE        VARCHAR2(4000),
    PARTNER_DESC        VARCHAR2(4000),
    SCORE               NUMBER,
    VERSION             VARCHAR2(4000),
    RISKS               VARCHAR2(4000),
    RESPONSE_TIME       DATE,
    TRACKING_ID         VARCHAR2(4000),
    CREATED_DATE        DATE,

    CONSTRAINT DE_CBC_THIRD_SYSTEM_SCORE_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_THIRD_SYSTEM_SCORE
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------DE_CBC_UW_CRITERIA----------------------
CREATE TABLE DE_CBC_UW_CRITERIA (
    ID                     NUMBER NOT NULL,
    PREV_POLICY_DECISION_ID NUMBER,
    PRODUCT_ID             NUMBER,
    "GROUP"             VARCHAR2(4000),
    ACTION                 VARCHAR2(4000),
    REASON_CODE            VARCHAR2(4000),
    REASON_DESCRIPTION     VARCHAR2(4000),
    RULE_CATEGORY          VARCHAR2(4000),
    APPLICANT_TYPE         VARCHAR2(4000),
    CREATED_DATE           DATE,

    CONSTRAINT DE_CBC_UW_CRITERIA_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_UW_CRITERIA
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------DE_CBC_WAY4----------------------
CREATE TABLE DE_CBC_WAY4 (
     ID                   NUMBER NOT NULL,
     APPLICANT_REFER_ID   NUMBER,
     CODE                 NUMBER,
     REQUEST_TIMESTAMP    VARCHAR2(4000),
     MESSAGE              VARCHAR2(4000),
     CONTRACT_NUMBER      VARCHAR2(4000),
     CONTRACT_STATUS      VARCHAR2(4000),
     CONTRACT_STATUS_CODE VARCHAR2(4000),
     DATE_OPEN            VARCHAR2(4000),
     PRODUCT_CODE         VARCHAR2(4000),
     CONTRACT_LIMIT       NUMBER,
     CREATED_DATE         DATE,

     CONSTRAINT DE_CBC_WAY4_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_DE_CBC_WAY4
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------ODS_APPLICATION----------------------
CREATE TABLE ODS_APPLICATION (
     ID                           NUMBER NOT NULL,
     CIF_NO                     VARCHAR2(4000),
     MAIN_IDENTIFICATION_NUMBER   VARCHAR2(4000),
     APPLICATION_DE_REF_NUMBER    VARCHAR2(4000),
     REQUEST_PAYLOAD              CLOB,
     UPDATED_DATETIME             TIMESTAMP,
     CONSTRAINT ODS_APPLICATION_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ODS_APPLICATION
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------ODS_APPLICATION_STATE----------------------
CREATE TABLE ODS_APPLICATION_STATE (
    ID                             NUMBER NOT NULL,
    APPLICATION_DE_REF_NUMBER      VARCHAR2(4000),
    SOURCE_SYSTEM_ID               VARCHAR2(4000),
    STATE                          VARCHAR2(4000),
    MESSAGE                        VARCHAR2(4000),
    CREATED_DATETIME               TIMESTAMP,
    UPDATED_DATETIME               TIMESTAMP,
    CONSTRAINT ODS_APPLICATION_STATE_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ODS_APPLICATION_STATE
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------ODS_INTEGRATION_EVENT_LOG----------------------
CREATE TABLE ODS_INTEGRATION_EVENT_LOG (
    ID                          NUMBER NOT NULL,
    APPLICATION_DE_REF_NUMBER   VARCHAR2(4000),
    APPLICANT_MAIN_ID           VARCHAR2(4000),
    APPLICANT_ID                VARCHAR2(4000),
    APPLICANT_TYPE              VARCHAR2(4000),
    CALL_TYPE                   VARCHAR2(4000),
    SYSTEM                      VARCHAR2(4000),
    REQUEST_PAYLOAD             CLOB,
    RESPONSE_PAYLOAD            CLOB,
    STATUS                      VARCHAR2(4000),
    START_DATETIME              TIMESTAMP,
    END_DATETIME                TIMESTAMP,
    CREATED_DATETIME            TIMESTAMP,

    CONSTRAINT ODS_INTEGRATION_EVENT_LOG_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ODS_INTEGRATION_EVENT_LOG
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------ODS_MODEL_EXECUTION_LOG----------------------
CREATE TABLE ODS_MODEL_EXECUTION_LOG (
     ID                         NUMBER NOT NULL,
     APPLICATION_DE_REF_NUMBER  VARCHAR2(4000) NOT NULL,
     CUSTOMER_ID                VARCHAR2(4000),
     CALL_TYPE                  VARCHAR2(4000),
     MODEL_NAME                 VARCHAR2(4000),
     INPUT                      CLOB,
     OUTPUT                     CLOB,
     CREATED_DATETIME           TIMESTAMP,
     CONSTRAINT ODS_MODEL_EXECUTION_LOG_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ODS_MODEL_EXECUTION_LOG
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------

-------------------ODS_PREVIOUS_POLICY_DECISION----------------------
CREATE TABLE ODS_PREVIOUS_POLICY_DECISION (
    ID NUMBER(22,0) NOT NULL,
    APPLICATION_DE_REF_NUMBER VARCHAR2(4000),
    APPLICANT_IDS VARCHAR2(4000),
    PHONE_NUMBER VARCHAR2(4000),
    RULE_ACTION VARCHAR2(4000),
    REASON_CODE VARCHAR2(4000),
    REASON_DESCRIPTION VARCHAR2(4000),
    RULE_CATEGORY VARCHAR2(4000),
    APPLICANT_TYPE VARCHAR2(4000),
    RESULT_DATE TIMESTAMP,
    CREATE_DATE TIMESTAMP,

    CONSTRAINT PK_ODS_PREVIOUS_POLICY_DECISION PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ODS_PREVIOUS_POLICY_DECISION
    START WITH 1
    INCREMENT BY 1;
-----------------------------------------